#!/usr/bin/env python3
"""Writing-style signals for Markdown prose, in Japanese and English.

The criteria, the defect each rule points at, and the manual review that outranks every count are
in the Hub's criteria document:

    https://github.com/Yoshiki0705/FSx-for-ONTAP-Adoption-Playbook/blob/main/docs/agent/writing-quality.md

A count is a symptom. Removing the pattern without fixing what it indicates only makes the defect
harder to see, so treat a finding as a question about the sentence, not as an edit to make.

Two levels:

  fail     D1 (bold markers that do not render), D2 (Japanese closing catchphrases), D5 (chat-style
           closings), D14 (bold inside a heading). Staged: a repository gates on them with --fail
           in the same pull request that clears its existing findings.
  warning  everything else. Counted, never gated.

Copying: this file is self-contained (stdlib only, imports nothing from its repository). A sibling
repository copies this one file, runs it as a CLI, and links to the criteria document above rather
than copying the rules into its own guidance.

    python3 ai_style_rules.py docs/               # findings, exit 0
    python3 ai_style_rules.py docs/ --summary     # counts by category, language and rule
    python3 ai_style_rules.py docs/ --fail        # exit 1 when a fail-level rule fires
    python3 ai_style_rules.py --selftest          # every rule fires on its positive, not its negative

D1 decides whether a `**` renders by implementing the CommonMark delimiter-run and emphasis
algorithm, ported from markdown-it 14.1.1. The Hub checks it against fixtures generated by
markdown-it itself, because the case it exists for (`**「X」**` beside a Japanese particle) is one
that reads correctly in the source and renders as literal asterisks.
"""

from __future__ import annotations

import argparse
import fnmatch
import html
import re
import sys
import unicodedata
from dataclasses import dataclass
from pathlib import Path

LANGS = ("ja", "en")
CATEGORY_FOR_LEVEL = {"fail": "ai-style", "warning": "ai-style-warn"}


@dataclass(frozen=True)
class Rule:
    id: str
    level: str  # "fail" or "warning"
    langs: tuple[str, ...]
    defect: str  # the underlying defect the pattern suggests, one Japanese sentence
    message: str
    positive: tuple[tuple[str, str], ...]  # (lang, document) that must fire
    negative: tuple[tuple[str, str], ...]  # (lang, document) that must not fire


@dataclass(frozen=True)
class Finding:
    line: int
    rule: str
    level: str
    message: str


_LONG_BOLD = "**太字**の文が続く。" * 260
_LONG_PLAIN = "太字のない文が続く。" * 260

RULES: tuple[Rule, ...] = (
    Rule(
        "D1",
        "fail",
        ("ja", "en"),
        "強調のつもりの箇所がアスタリスクのまま表示され、読者には壊れた文書に見える。",
        "'**' does not render as bold here; move the marker outside the brackets or reword",
        (("ja", "上は**「自分の構成」**で引く。\n"),),
        (("ja", "次は**自分の構成**で引く。\n"),),
    ),
    Rule(
        "D2",
        "fail",
        ("ja",),
        "決め台詞が主張の代わりになっていて、何がどうなるかが書かれていない。",
        "closing catchphrase; state what happens instead",
        (("ja", "速さが核心です。\n"), ("ja", "結論はこの点に尽きる。\n")),
        (("ja", "容量が先に尽きます。\n"), ("ja", "設計の核心部分を説明する。\n")),
    ),
    Rule(
        "D3",
        "warning",
        ("ja",),
        "否定で持ち上げる対比構文で、言いたい内容そのものが後回しになっている。",
        "contrast frame ('not merely X'); state the point directly",
        (("ja", "単なるコピーではなく差分転送だ。\n"),),
        (("ja", "単にコピーする。\n"),),
    ),
    Rule(
        "D4",
        "warning",
        ("ja",),
        "意外性を演出する副詞で、前提との差分が明示されていない。",
        "'実は' implies a reveal; state the difference from the assumption",
        (("ja", "実は設定が要る。\n"),),
        (("ja", "事実は次のとおり。\n"),),
    ),
    Rule(
        "D5",
        "fail",
        ("ja", "en"),
        "会話の定型の締めが残っていて、文書が読者ではなく対話相手に向いている。",
        "chat-style closing; end when the content ends",
        (("ja", "ご不明な点があればどうぞ。\n"), ("en", "I hope this helps.\n")),
        (("ja", "不明な点を表にまとめた。\n"), ("en", "Let the job finish.\n")),
    ),
    Rule(
        "D6",
        "warning",
        ("en",),
        "対比構文で持ち上げていて、言いたい内容そのものが後回しになっている。",
        "'not just X but Y'; say Y",
        (("en", "It is not just fast but cheap.\n"),),
        (("en", "It is not fast.\n"),),
    ),
    Rule(
        "D7",
        "warning",
        ("en",),
        "意義を語る言い回しが、具体的な役割や挙動の説明に置き換わっていない。",
        "significance phrasing; say what the thing does",
        (("en", "The SVM serves as a boundary.\n"),),
        (("en", "The SVM is a boundary.\n"),),
    ),
    Rule(
        "D9",
        "warning",
        ("ja", "en"),
        "要約の予告や注意喚起の前置きがあり、直前の内容を繰り返している。",
        "signposting; delete it or replace it with the new information",
        (("en", "In summary, use NFS.\n"), ("ja", "まとめると、NFS を使う。\n")),
        (("en", "The summary table lists it.\n"),),
    ),
    Rule(
        "D10",
        "warning",
        ("ja", "en"),
        "手順を簡単だと形容していて、失敗する条件が書かれていない。",
        "a numbered step called simple or quick; state the precondition instead",
        (("en", "1. Simply run the script.\n"), ("ja", "1. 簡単に設定できる。\n")),
        (("en", "- Simply run the script.\n"),),
    ),
    Rule(
        "D11",
        "warning",
        ("ja", "en"),
        "出典のない一般論で、誰がどこで述べたかを読者が確かめられない。",
        "unattributed generality; cite the source or drop the claim",
        (
            ("ja", "多くの企業が採用している。\n"),
            ("en", "Studies show it is common.\n"),
        ),
        (("ja", "[調査](https://example.com/a)では多くの企業が採用している。\n"),),
    ),
    Rule(
        "D12",
        "warning",
        ("ja",),
        "ラベル付きリストで、属性が 2 つ以上なら表、そうでなければ地の文で書ける内容になっている。",
        "labeled list item; use a table for 2+ attributes, otherwise prose",
        (("ja", "- **課題**: 遅い\n"), ("ja", "- **課題** — 遅い\n")),
        (("ja", "- 課題は遅いこと\n"),),
    ),
    Rule(
        "D13",
        "warning",
        ("ja", "en"),
        "絵文字が見出しや箇条の装飾として使われ、意味を運んでいない。",
        "decorative emoji in a list item or heading",
        (("ja", "- ✅ 完了\n"), ("ja", "## 🚀 はじめかた\n")),
        (("ja", "| 状態 | ✅ |\n|---|---|\n| 完了 | ✅ |\n"),),
    ),
    Rule(
        "D14",
        "fail",
        ("ja", "en"),
        "見出しの中の太字で、見出しの階層と強調が二重になり、目次やアンカーにも記号が残る。",
        "bold inside a heading; the heading level already carries the emphasis",
        (("ja", "## **重要**な設定\n"),),
        (("ja", "## 重要な設定\n"),),
    ),
    Rule(
        "D15",
        "warning",
        ("ja", "en"),
        "太字が多すぎるか文全体が太字で、本当に見落とすと壊れる条件が埋もれている。",
        "bold density or a whole-line bold sentence",
        (("ja", "**この操作は戻せない。**\n"), ("ja", _LONG_BOLD + "\n")),
        (("ja", "この操作は**戻せない**。\n"), ("ja", _LONG_PLAIN + "\n")),
    ),
    Rule(
        "D17",
        "warning",
        ("ja", "en"),
        "構造が中身に釣り合っておらず、1 項目のリストや本文のない見出しが並んでいる。",
        "a one-item list, or a heading with no content before a deeper heading",
        (
            ("ja", "前の段落。\n\n- 1 つだけ\n\n次の段落。\n"),
            ("ja", "## 親\n\n### 子\n\n本文。\n"),
        ),
        (("ja", "前の段落。\n\n- 1 つ目\n- 2 つ目\n\n次の段落。\n"),),
    ),
    Rule(
        "D18",
        "warning",
        ("ja", "en"),
        "em ダッシュで節をつないでいて、文の関係（理由・例・言い換え）が明示されていない。",
        "em dash; state the relation (because / for example / that is)",
        (("ja", "転送 — 差分のみ\n"),),
        (("ja", "転送（差分のみ）\n"),),
    ),
    Rule(
        "D19",
        "warning",
        ("ja",),
        "コードや表の直前を「〜します:」で止めていて、何が得られるかが書かれていない。",
        "a sentence ending in a colon before a block; say what the block shows",
        (("ja", "次を実行します:\n\n```bash\nls\n```\n"),),
        (("ja", "使用方法:\n\n```bash\nls\n```\n"),),
    ),
    Rule(
        "D20",
        "warning",
        ("ja",),
        "冗長な言い回しで、短く言える動詞が名詞化されている。",
        "redundant phrasing (することができる / まず最初に / の設定を行う)",
        (("ja", "設定することができます。\n"),),
        (("ja", "設定できます。\n"),),
    ),
    Rule(
        "D23",
        "warning",
        ("ja",),
        "推量が二重になっていて、確認済みか未確認かが読み取れない。",
        "doubled hedge; say whether it is confirmed",
        (("ja", "遅い可能性があると考えられる。\n"),),
        (("ja", "遅い可能性がある。\n"),),
    ),
    Rule(
        "D24",
        "warning",
        ("ja", "en"),
        "程度を形容詞で語っていて、数値と測定環境が示されていない。",
        "degree adjective; give the number and the environment",
        (("ja", "飛躍的に向上した。\n"), ("en", "The copy is blazing fast.\n")),
        (("ja", "3.2 倍に向上した（同一環境）。\n"),),
    ),
)

RULE_BY_ID = {rule.id: rule for rule in RULES}

# ---------------------------------------------------------------- simple line patterns

_I = re.IGNORECASE
LINE_PATTERNS: dict[str, dict[str, re.Pattern[str]]] = {
    # 「尽きる」 is narrowed to a preceding demonstrative or こと/点. Without it, 「容量が先に尽きます」
    # (capacity runs out) is reported, which is a literal statement and not a catchphrase.
    "D2": {
        "ja": re.compile(
            r"(?:が核心(?:です|だ)?|が肝(?:です|だ)?|が命(?:です|だ)?)(?:。|$)"
            r"|(?:こと|点|これ|それ)に尽き(?:る|ます)(?:。|」|$)|結局のところ"
        )
    },
    "D3": {"ja": re.compile(r"単なる[^。]*ではな|ただの[^。]*ではなく")},
    # 現実は / 事実は / 真実は / 結果は are ordinary nouns followed by a particle.
    "D4": {"ja": re.compile(r"(?<![事真果現])実は")},
    "D5": {
        "ja": re.compile(r"お役に立てれば|ご不明な点|いかがでしたか"),
        "en": re.compile(r"\bI hope this helps\b|\bLet me know\b|\bCertainly!", _I),
    },
    "D6": {"en": re.compile(r"\bnot\s+(?:just|only|merely)\b[^.]*?\bbut\b", _I)},
    "D7": {
        "en": re.compile(
            r"\b(?:serves|stands)\s+as\b"
            r"|\bplays?\s+an?\s+(?:key|crucial|vital|pivotal)\s+role\b"
            r"|\bis\s+a\s+testament\s+to\b",
            _I,
        )
    },
    "D9": {
        "ja": re.compile(r"まとめると"),
        "en": re.compile(
            r"\bin\s+(?:summary|conclusion)\b"
            r"|\bit'?s\s+(?:important|worth)\s+(?:to\s+note|noting)\b|\bplease\s+note\b",
            _I,
        ),
    },
    "D11": {
        "ja": re.compile(
            r"専門家によると|一般的に(?:は|言われ)|多くの(?:企業|組織)|と言われてい"
        ),
        "en": re.compile(
            r"\bexperts?\s+(?:say|agree|argue)\b|\bindustry\s+reports\b|\bstudies\s+show\b",
            _I,
        ),
    },
    "D20": {
        "ja": re.compile(r"することができ|まず最初に|の(?:変更|設定|確認|実行)を行")
    },
    "D23": {"ja": re.compile(r"可能性があると考えられ|と思われる可能性")},
    # 劇的に速 / 大幅に改善 / dramatically faster are already sales-vocabulary in the Hub audit.
    "D24": {
        "ja": re.compile(r"劇的に(?!速)|飛躍的に|大幅に(?:高速|向上)"),
        "en": re.compile(r"\bblazing\b|\bdramatically\b(?!\s+(?:faster|improve))", _I),
    },
}
D10_PATTERNS = {
    "ja": re.compile(r"簡単に|すぐに"),
    "en": re.compile(r"\b(?:simply|just|easily)\b", _I),
}
D12_PATTERN = re.compile(
    r"^\s*(?:[-*+]|\d+[.)])\s+\*\*[^*\n]+\*\*\s*(?:[:：—–]|-\s)"
    r"|^\s*(?:[-*+]|\d+[.)])\s+\*\*[^*\n]+[:：]\*\*"
)
EMOJI = re.compile("[\U0001f300-\U0001faff\u2600-\u27bf\u2b00-\u2bff\u2300-\u23ff]")
D15_LINE = re.compile(r"^\*\*[^*]+\*\*[。.]?$")
D15_SPAN = re.compile(r"\*\*[^*\n]+\*\*")
D15_MIN_CHARS = 2000
D15_MAX_PER_1000 = 5.0
D19_PATTERN = re.compile(r"(?:ます|です|する|した)[:：]\s*$")

HEADING = re.compile(r"^ {0,3}(#{1,6})(?:[ \t]|$)")
LIST_ITEM = re.compile(r"^(\s*)(?:[-*+]|\d{1,9}[.)])(?:[ \t]+|$)")
NUMBERED_ITEM = re.compile(r"^\s*\d+[.)]\s")
FENCE = re.compile(r"^\s*(`{3,}|~{3,})")
QUOTE_PREFIX = re.compile(r"^(?: {0,3}>[ ]?)+")
URL = re.compile(r"https?://\S+")
SWITCHER_START = "<!-- lang-switcher:start -->"
SWITCHER_END = "<!-- lang-switcher:end -->"

# ---------------------------------------------------------------- language


_PATH_LANGS = {"ja", "en", "ko", "zh-CN", "zh-TW", "fr", "de", "es"}
_STEM_LANG = re.compile(r"[-._](ja|en)$")
_KANA = re.compile(r"[\u3040-\u30ff]")
_ASCII_LETTER = re.compile(r"[A-Za-z]")
# Kana as a share of kana plus ASCII letters. Japanese prose here measures 0.3 or more even when
# dense with commands and product names; an English file quoting Japanese examples measures under
# 0.01. A bare kana count read such files as Japanese and applied the Japanese rules to English.
_KANA_SHARE = 0.05


def language_of(relpath: str, text: str) -> str:
    """The document's language: a path component, then a `-ja`/`.en` stem suffix, then the text."""
    parts = Path(relpath).parts
    for part in parts[:-1]:
        if part in _PATH_LANGS:
            return part
    suffix = _STEM_LANG.search(Path(relpath).stem)
    if suffix:
        return suffix.group(1)
    kana = len(_KANA.findall(text))
    letters = len(_ASCII_LETTER.findall(text))
    return "ja" if kana >= 10 and kana >= _KANA_SHARE * (kana + letters) else "en"


# ---------------------------------------------------------------- shared preprocessing


def _blank_frontmatter(lines: list[str]) -> list[str]:
    """Frontmatter is metadata, not prose. Blanked so line numbers stay those of the file."""
    if not lines or lines[0].strip() != "---":
        return lines
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return [""] * (index + 1) + lines[index + 1 :]
    return lines


def _mask_code_spans(line: str) -> str:
    """Replace each code span, backticks included, with spaces of the same width."""
    out: list[str] = []
    i = 0
    n = len(line)
    while i < n:
        if line[i] != "`":
            out.append(line[i])
            i += 1
            continue
        j = i
        while j < n and line[j] == "`":
            j += 1
        run = j - i
        k = j
        close = -1
        while k < n:
            if line[k] == "`":
                m = k
                while m < n and line[m] == "`":
                    m += 1
                if m - k == run:
                    close = m
                    break
                k = m
            else:
                k += 1
        if close < 0:
            out.append(line[i:j])
            i = j
        else:
            out.append(" " * (close - i))
            i = close
    return "".join(out)


@dataclass
class _Line:
    number: int
    raw: str
    masked: str  # prose only: code spans, comments and URLs replaced with spaces
    kind: str  # skip / blank / code / heading / list / table / para
    level: int = 0  # heading level


def _prose_view(lines: list[str]) -> list[_Line]:
    """Classify each line and mask what is not prose, for every rule except D1."""
    view: list[_Line] = []
    fence: str | None = None
    in_comment = False
    in_switcher = False
    for number, raw in enumerate(lines, start=1):
        fence_match = FENCE.match(raw)
        if fence is not None:
            if fence_match:
                candidate = fence_match.group(1)
                if (
                    candidate[0] == fence[0]
                    and len(candidate) >= len(fence)
                    and set(raw.strip()) == {fence[0]}
                ):
                    fence = None
            view.append(_Line(number, raw, "", "code"))
            continue
        if fence_match and not in_comment:
            fence = fence_match.group(1)
            view.append(_Line(number, raw, "", "code"))
            continue
        if SWITCHER_START in raw:
            in_switcher = True
        if in_switcher:
            if SWITCHER_END in raw:
                in_switcher = False
            view.append(_Line(number, raw, "", "skip"))
            continue
        masked = _mask_code_spans(raw)
        chars = list(masked)
        position = 0
        while position < len(masked):
            if in_comment:
                end = masked.find("-->", position)
                stop = len(masked) if end < 0 else end + 3
                for index in range(position, stop):
                    chars[index] = " "
                if end < 0:
                    break
                in_comment = False
                position = stop
                continue
            start = masked.find("<!--", position)
            if start < 0:
                break
            in_comment = True
            position = start
        masked = URL.sub(lambda m: " " * len(m.group()), "".join(chars))
        body = QUOTE_PREFIX.sub("", masked)
        if not masked.strip():
            view.append(_Line(number, raw, "", "blank" if not raw.strip() else "skip"))
            continue
        heading = HEADING.match(body)
        if heading:
            view.append(_Line(number, raw, body, "heading", len(heading.group(1))))
        elif LIST_ITEM.match(body):
            view.append(_Line(number, raw, body, "list"))
        elif body.lstrip().startswith("|"):
            view.append(_Line(number, raw, body, "table"))
        else:
            view.append(_Line(number, raw, body, "para"))
    return view


def _first_visible_after_marker(line: _Line) -> str:
    if line.kind == "heading":
        rest = line.masked.lstrip()[line.level :]
    else:
        match = LIST_ITEM.match(line.masked)
        rest = line.masked[match.end() :] if match else ""
        rest = re.sub(r"^\[[ xX]\]\s*", "", rest)
    rest = rest.lstrip()
    return rest[:1]


def _structural_findings(view: list[_Line], lang: str) -> list[Finding]:
    found: list[Finding] = []

    def add(rule_id: str, line: int, message: str | None = None) -> None:
        rule = RULE_BY_ID[rule_id]
        found.append(Finding(line, rule_id, rule.level, message or rule.message))

    content = [line for line in view if line.kind not in ("skip", "blank")]
    for line in view:
        if line.kind in ("skip", "blank", "code"):
            continue
        text = line.masked.rstrip()
        for rule_id, by_lang in LINE_PATTERNS.items():
            pattern = by_lang.get(lang)
            if pattern is None or lang not in RULE_BY_ID[rule_id].langs:
                continue
            if rule_id == "D11" and URL.search(line.raw):
                continue
            if pattern.search(text):
                add(rule_id, line.number)
        if NUMBERED_ITEM.match(text) and D10_PATTERNS[lang].search(text):
            add("D10", line.number)
        if lang == "ja" and line.kind == "list" and D12_PATTERN.search(text):
            add("D12", line.number)
        if line.kind in ("list", "heading") and EMOJI.match(
            _first_visible_after_marker(line)
        ):
            add("D13", line.number)
        if line.kind == "heading" and ("**" in text or "__" in text):
            add("D14", line.number)
        if line.kind == "para" and D15_LINE.match(text.strip()):
            add("D15", line.number)
        dashes = text.count("\u2014")
        if dashes:
            add(
                "D18",
                line.number,
                f"{RULE_BY_ID['D18'].message} ({dashes} on this line)",
            )

    # D15 (a): bold density over the whole document.
    visible = sum(len(re.sub(r"\s", "", line.masked)) for line in content)
    spans = sum(len(D15_SPAN.findall(line.masked)) for line in content)
    if visible >= D15_MIN_CHARS and spans * 1000 / visible > D15_MAX_PER_1000:
        add(
            "D15",
            1,
            f"bold density {spans * 1000 / visible:.1f} per 1,000 characters "
            f"(over {D15_MAX_PER_1000})",
        )

    # D17 (a): a top-level list holding a single item. (b): a heading followed directly by a
    # deeper heading, with nothing in between.
    def item_indent(line: _Line) -> int | None:
        match = LIST_ITEM.match(line.masked) if line.kind == "list" else None
        return len(match.group(1)) if match else None

    def indent_of(line: _Line) -> int:
        body = QUOTE_PREFIX.sub("", line.raw)
        return len(body) - len(body.lstrip())

    index = 0
    while index < len(view):
        base = item_indent(view[index])
        if base is None or base > 3:
            index += 1
            continue
        start = view[index].number
        items = 1
        index += 1
        while index < len(view):
            current = view[index]
            sibling = item_indent(current)
            if current.kind == "blank":
                following = next(
                    (v for v in view[index + 1 :] if v.kind != "blank"), None
                )
                if following is None:
                    break
                following_item = item_indent(following)
                if not (
                    following_item is not None
                    and abs(following_item - base) <= 1
                    or indent_of(following) >= base + 2
                ):
                    break
            elif current.kind == "heading" or (
                current.kind in ("code", "skip") and indent_of(current) < base + 2
            ):
                break
            elif sibling is not None and abs(sibling - base) <= 1:
                items += 1
            index += 1
        if items == 1:
            add("D17", start)
    for position, line in enumerate(content):
        if line.kind != "heading" or position + 1 >= len(content):
            continue
        following = content[position + 1]
        if following.kind == "heading" and following.level > line.level:
            add("D17", line.number, "heading with no content before a deeper heading")

    # D19: a Japanese sentence that stops at a colon right before a block.
    if lang == "ja":
        for position, line in enumerate(view):
            if line.kind not in ("para", "list") or not D19_PATTERN.search(line.masked):
                continue
            following = next((v for v in view[position + 1 :] if v.raw.strip()), None)
            if following is not None and (
                FENCE.match(following.raw)
                or LIST_ITEM.match(following.raw)
                or following.raw.lstrip().startswith("|")
            ):
                add("D19", line.number)
    return found


# ---------------------------------------------------------------- D1: CommonMark emphasis

# markdown-it 14.1.1 `isWhiteSpace`, which is narrower than Unicode Zs plus the ASCII controls.
_WHITESPACE = frozenset(
    "\t\n\x0b\x0c\r \xa0\u1680\u202f\u205f\u3000"
    + "".join(chr(c) for c in range(0x2000, 0x200B))
)
_ASCII_PUNCT = frozenset("!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~")


def _is_punct(char: str) -> bool:
    """markdown-it `isMdAsciiPunct || isPunctChar` (Unicode P and S).

    markdown-it reads one UTF-16 code unit, so a character outside the BMP is a lone surrogate to
    it and is neither punctuation nor whitespace. That is mirrored here: an emoji next to `**` is
    a letter for flanking purposes, whatever its Unicode category.
    """
    if char in _ASCII_PUNCT:
        return True
    if ord(char) > 0xFFFF:
        return False
    return unicodedata.category(char)[0] in "PS"


_ATTR = r"(?:\s+[a-zA-Z_:][a-zA-Z0-9:._-]*(?:\s*=\s*(?:[^\"'=<>`\x00-\x20]+|'[^']*'|\"[^\"]*\"))?)"
_OPEN_TAG = r"<[A-Za-z][A-Za-z0-9\-]*" + _ATTR + r"*\s*/?>"
_CLOSE_TAG = r"</[A-Za-z][A-Za-z0-9\-]*\s*>"
HTML_TAG = re.compile(
    r"(?:" + _OPEN_TAG + "|" + _CLOSE_TAG + r"|<!---?>|<!--(?:[^-]|-[^-]|--[^>])*-->"
    r"|<[?][\s\S]*?[?]>|<![A-Za-z][^>]*>|<!\[CDATA\[[\s\S]*?\]\]>)"
)
HTML_OPEN_CLOSE = re.compile(r"(?:" + _OPEN_TAG + "|" + _CLOSE_TAG + r")")
AUTOLINK = re.compile(r"<[a-zA-Z][a-zA-Z0-9+.\-]{1,31}:[^<>\x00-\x20]*>")
EMAIL_AUTOLINK = re.compile(
    r"<[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?"
    r"(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*>"
)
ENTITY = re.compile(
    r"&(?:#[xX][0-9a-fA-F]{1,6}|#[0-9]{1,7}|[A-Za-z][A-Za-z0-9]{1,31});"
)
_BLOCK_NAMES = (
    "address|article|aside|base|basefont|blockquote|body|caption|center|col|colgroup|dd|details|"
    "dialog|dir|div|dl|dt|fieldset|figcaption|figure|footer|form|frame|frameset|h1|h2|h3|h4|h5|"
    "h6|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|nav|noframes|ol|optgroup|"
    "option|p|param|search|section|summary|table|tbody|td|tfoot|th|thead|title|tr|track|ul"
)
HTML_BLOCKS: tuple[tuple[re.Pattern[str], re.Pattern[str] | None, bool], ...] = (
    (
        re.compile(r"^<(script|pre|style|textarea)(?=(\s|>|$))", re.IGNORECASE),
        re.compile(r"</(script|pre|style|textarea)>", re.IGNORECASE),
        True,
    ),
    (re.compile(r"^<!--"), re.compile(r"-->"), True),
    (re.compile(r"^<\?"), re.compile(r"\?>"), True),
    (re.compile(r"^<![A-Z]"), re.compile(r">"), True),
    (re.compile(r"^<!\[CDATA\["), re.compile(r"\]\]>"), True),
    (
        re.compile(r"^</?(" + _BLOCK_NAMES + r")(?=(\s|/?>|$))", re.IGNORECASE),
        None,
        True,
    ),
    (re.compile(r"^(?:" + _OPEN_TAG + "|" + _CLOSE_TAG + r")\s*$"), None, False),
)
THEMATIC_BREAK = re.compile(
    r"^ {0,3}(?:(?:\*[ \t]*){3,}|(?:-[ \t]*){3,}|(?:_[ \t]*){3,})$"
)
SETEXT = re.compile(r"^ {0,3}(?:=+|-+)[ \t]*$")
ATX = re.compile(r"^ {0,3}(#{1,6})(?:[ \t]+(.*?))?(?:[ \t]+#+)?[ \t]*$")
FENCE_OPEN = re.compile(r"^ {0,3}(`{3,}|~{3,})(.*)$")
BULLET = re.compile(r"^( {0,3})([*+-])([ \t]+|$)")
ORDERED = re.compile(r"^( {0,3})(\d{1,9})([.)])([ \t]+|$)")
REFERENCE = re.compile(r"^ {0,3}\[((?:[^\]\\]|\\.)+)\]:")


def _norm_label(label: str) -> str:
    return " ".join(label.split()).casefold()


def _indent(text: str) -> int:
    return len(text) - len(text.lstrip(" "))


def _list_marker(rest: str):
    """(width, empty, ordered_start) for a list marker at the start of `rest`, else None."""
    if THEMATIC_BREAK.match(rest):
        return None
    match = BULLET.match(rest) or ORDERED.match(rest)
    if not match:
        return None
    marker_end = match.end(len(match.groups()) - 1)
    spaces = match.group(len(match.groups()))
    empty = not rest[match.end() :].strip()
    if empty or len(spaces) > 4:
        width = marker_end + 1
    else:
        width = marker_end + len(spaces)
    start = int(match.group(2)) if match.re is ORDERED else None
    return width, empty, start


def _html_block_type(rest: str) -> int | None:
    if _indent(rest) >= 4:
        return None
    text = rest.lstrip(" ")
    if not text.startswith("<"):
        return None
    for index, (opener, _closer, _interrupts) in enumerate(HTML_BLOCKS):
        if opener.search(text):
            return index
    return None


def _interrupts_paragraph(rest: str) -> bool:
    """Whether `rest` starts a block that ends an open paragraph (lazy lines use this too)."""
    if not rest.strip():
        return True
    if _indent(rest) >= 4:
        return False
    if (
        ATX.match(rest)
        or FENCE_OPEN.match(rest)
        or rest.lstrip(" ").startswith(">")
        or THEMATIC_BREAK.match(rest)
    ):
        return True
    html_type = _html_block_type(rest)
    if html_type is not None and HTML_BLOCKS[html_type][2]:
        return True
    marker = _list_marker(rest)
    return bool(marker and not marker[1] and marker[2] in (None, 1))


def _split_cells(row: str) -> list[str]:
    """markdown-it `escapedSplit`, with the leading and trailing empty cell dropped."""
    cells: list[str] = []
    current = ""
    last = 0
    escaped = False
    for pos, char in enumerate(row):
        if char == "|":
            if not escaped:
                cells.append(current + row[last:pos])
                current = ""
                last = pos + 1
            else:
                current += row[last : pos - 1]
                last = pos
        escaped = char == "\\"
    cells.append(current + row[last:])
    if cells and cells[0] == "":
        cells.pop(0)
    if cells and cells[-1] == "":
        cells.pop()
    return cells


def _delimiter_row_columns(row: str) -> int | None:
    text = row.strip()
    if not text or text[0] not in "|-:" or len(text) < 2:
        return None
    if text[1] not in "|-: \t" or (text[0] == "-" and text[1] in " \t"):
        return None
    if any(char not in "|-: \t" for char in text):
        return None
    columns = row.split("|")
    count = 0
    for index, column in enumerate(columns):
        cell = column.strip()
        if not cell:
            if index in (0, len(columns) - 1):
                continue
            return None
        if not re.fullmatch(r":?-+:?", cell):
            return None
        count += 1
    return count


def _match_containers(raw: str, stack: list[tuple[str, int]]) -> tuple[int, int]:
    """How many open containers this line continues, and where its content starts."""
    pos = 0
    for depth, (kind, width) in enumerate(stack):
        rest = raw[pos:]
        if kind == "quote":
            match = re.match(r" {0,3}>", rest)
            if not match:
                return depth, pos
            pos += match.end()
            if raw[pos : pos + 1] == " ":
                pos += 1
        else:
            if not rest.strip():
                continue
            if _indent(rest) < width:
                return depth, pos
            pos += width
    return len(stack), pos


def _blocks(lines: list[str]) -> list[tuple[str, list[tuple[int, str]]]]:
    """Split a document into ("inline" | "raw", [(line number, text), ...]) blocks.

    The container and leaf rules are the subset of CommonMark this repository's documents use:
    block quotes, lists, fences, indented code, ATX and setext headings, thematic breaks, HTML
    blocks, GFM tables and paragraphs. Indented code inside a list item, and reference definitions
    spanning several lines, are approximations.
    """
    out: list[tuple[str, list[tuple[int, str]]]] = []
    stack: list[tuple[str, int]] = []
    leaf: dict | None = None

    def close() -> None:
        nonlocal leaf
        if leaf is None:
            return
        if leaf["kind"] == "para" and leaf["lines"]:
            out.append(("inline", leaf["lines"]))
        elif leaf["kind"] == "html":
            out.append(("raw", leaf["lines"]))
        leaf = None

    total = len(lines)
    index = 0
    while index < total:
        number = index + 1
        raw = lines[index].expandtabs(4)
        matched, pos = _match_containers(raw, stack)
        rest = raw[pos:]
        blank = not rest.strip()

        if matched < len(stack):
            if (
                leaf is not None
                and leaf["kind"] == "para"
                and not _interrupts_paragraph(rest)
            ):
                leaf["lines"].append((number, rest.strip()))
                index += 1
                continue
            close()
            del stack[matched:]
        elif leaf is not None and leaf["kind"] == "fence":
            text = rest.lstrip(" ")
            if (
                _indent(rest) < 4
                and text.startswith(leaf["marker"][0] * len(leaf["marker"]))
                and set(text.rstrip()) == {leaf["marker"][0]}
            ):
                leaf = None
            index += 1
            continue
        elif leaf is not None and leaf["kind"] == "html":
            closer = HTML_BLOCKS[leaf["type"]][1]
            if closer is None:
                if blank:
                    close()
                    index += 1
                    continue
                leaf["lines"].append((number, rest))
            else:
                leaf["lines"].append((number, rest))
                if closer.search(rest):
                    close()
            index += 1
            continue
        elif leaf is not None and leaf["kind"] == "table":
            if not blank and _indent(rest) < 4 and not _interrupts_paragraph(rest):
                cells = _split_cells(rest.strip())
                for cell in cells[: leaf["columns"]]:
                    out.append(("inline", [(number, cell.strip())]))
                index += 1
                continue
            leaf = None
        elif leaf is not None and leaf["kind"] == "code":
            if blank or _indent(rest) >= 4:
                index += 1
                continue
            leaf = None

        # New containers.
        while True:
            if _indent(rest) >= 4:
                break
            stripped = rest.lstrip(" ")
            if stripped.startswith(">"):
                close()
                stack.append(("quote", 0))
                rest = stripped[1:]
                rest = rest.removeprefix(" ")
                continue
            marker = _list_marker(rest)
            if marker is None:
                break
            width, empty, start = marker
            if (
                leaf is not None
                and leaf["kind"] == "para"
                and (empty or start not in (None, 1))
            ):
                break
            close()
            stack.append(("item", width))
            rest = rest[width:] if len(rest) >= width else ""
        blank = not rest.strip()

        if blank:
            close()
            index += 1
            continue
        if leaf is not None and leaf["kind"] == "para":
            if SETEXT.match(rest):
                close()
                index += 1
                continue
            if not _interrupts_paragraph(rest) and not _table_starts(
                lines, index, rest, stack
            ):
                leaf["lines"].append((number, rest.strip()))
                index += 1
                continue
        if _indent(rest) >= 4:
            close()
            leaf = {"kind": "code"}
            index += 1
            continue
        fence = FENCE_OPEN.match(rest)
        if fence and not (fence.group(1)[0] == "`" and "`" in fence.group(2)):
            close()
            leaf = {"kind": "fence", "marker": fence.group(1)}
            index += 1
            continue
        heading = ATX.match(rest)
        if heading:
            close()
            out.append(("inline", [(number, (heading.group(2) or "").strip())]))
            index += 1
            continue
        if THEMATIC_BREAK.match(rest):
            close()
            index += 1
            continue
        html_type = _html_block_type(rest)
        if html_type is not None and (HTML_BLOCKS[html_type][2] or leaf is None):
            close()
            closer = HTML_BLOCKS[html_type][1]
            if closer is not None and closer.search(rest):
                out.append(("raw", [(number, rest)]))
            else:
                leaf = {"kind": "html", "type": html_type, "lines": [(number, rest)]}
            index += 1
            continue
        columns = _table_starts(lines, index, rest, stack)
        if columns:
            close()
            for cell in _split_cells(rest.strip()):
                out.append(("inline", [(number, cell.strip())]))
            leaf = {"kind": "table", "columns": columns}
            index += 2
            continue
        if leaf is None and REFERENCE.match(rest):
            index += 1
            continue
        close()
        leaf = {"kind": "para", "lines": [(number, rest.strip())]}
        index += 1
    close()
    return out


def _table_starts(lines: list[str], index: int, rest: str, stack) -> int | None:
    """Column count when `rest` is a table header and the next line its delimiter row."""
    if "|" not in rest or index + 1 >= len(lines) or _indent(rest) >= 4:
        return None
    following = lines[index + 1].expandtabs(4)
    matched, pos = _match_containers(following, stack)
    if matched < len(stack):
        return None
    columns = _delimiter_row_columns(following[pos:])
    if not columns or _indent(following[pos:]) >= 4:
        return None
    header = _split_cells(rest.strip())
    return columns if len(header) == columns else None


def _reference_labels(lines: list[str]) -> set[str]:
    return {
        _norm_label(match.group(1))
        for line in lines
        if (match := REFERENCE.match(QUOTE_PREFIX.sub("", line.lstrip())))
    }


class _Inline:
    """The inline pass of markdown-it 14.1.1, reduced to what decides whether a `*` renders."""

    def __init__(self, src: str, refs: set[str]) -> None:
        self.src = src
        self.refs = refs
        self.items: list[list] = []  # [visible text, source index, delimiter or None]
        self.token = 0

    def emit(self, text: str, at: int) -> None:
        self.items.append([text, at, None])
        self.token += 1

    def scope(self, start: int, end: int) -> None:
        src = self.src
        delimiters: list[dict] = []
        pos = start
        while pos < end:
            char = src[pos]
            if char == "*":
                run_end = pos
                while run_end < end and src[run_end] == "*":
                    run_end += 1
                last = src[pos - 1] if pos > 0 else " "
                following = src[run_end] if run_end < end else " "
                last_punct, next_punct = _is_punct(last), _is_punct(following)
                last_space, next_space = last in _WHITESPACE, following in _WHITESPACE
                left = not next_space and (not next_punct or last_space or last_punct)
                right = not last_space and (not last_punct or next_space or next_punct)
                for at in range(pos, run_end):
                    delimiter = {
                        "length": run_end - pos,
                        "token": self.token,
                        "end": -1,
                        "open": left,
                        "close": right,
                        "matched": False,
                    }
                    delimiters.append(delimiter)
                    self.items.append(["*", at, delimiter])
                    self.token += 1
                pos = run_end
                continue
            if char == "\\" and pos + 1 < end:
                following = src[pos + 1]
                if following in _ASCII_PUNCT:
                    self.emit(following, pos + 1)
                    pos += 2
                    continue
                if following == "\n":
                    self.emit("\n", pos + 1)
                    pos += 2
                    continue
            if char == "`":
                run_end = pos
                while run_end < end and src[run_end] == "`":
                    run_end += 1
                run = run_end - pos
                scan = run_end
                closed = -1
                while scan < end:
                    found = src.find("`" * run, scan, end)
                    if found < 0:
                        break
                    tail = found + run
                    while tail < end and src[tail] == "`":
                        tail += 1
                    if tail - found == run:
                        closed = tail
                        break
                    scan = tail
                if closed < 0:
                    self.emit(src[pos:run_end], pos)
                    pos = run_end
                else:
                    self.emit(
                        "", pos
                    )  # code renders inside <code>, which the metric drops
                    pos = closed
                continue
            if char == "!" and src[pos + 1 : pos + 2] == "[":
                link = self.link(pos + 1, end)
                if link is not None:
                    self.emit(
                        "", pos
                    )  # alt text lives in an attribute, which is not visible
                    pos = link[2]
                    continue
            if char == "[":
                link = self.link(pos, end)
                if link is not None:
                    label_start, label_end, link_end = link
                    self.emit("", pos)
                    self.scope(label_start, label_end)
                    self.emit("", label_end)
                    pos = link_end
                    continue
            if char == "<":
                autolink = AUTOLINK.match(src, pos, end) or EMAIL_AUTOLINK.match(
                    src, pos, end
                )
                if autolink:
                    self.emit(autolink.group()[1:-1], pos)
                    pos = autolink.end()
                    continue
                tag = HTML_TAG.match(src, pos, end)
                if tag:
                    text = tag.group().lower()
                    if re.match(r"<(code|pre)[\s>]", text):
                        self.emit("\x01", pos)
                    elif re.match(r"</(code|pre)>", text):
                        self.emit("\x02", pos)
                    else:
                        self.emit("", pos)
                    pos = tag.end()
                    continue
            if char == "&":
                entity = ENTITY.match(src, pos, end)
                if entity:
                    decoded = html.unescape(entity.group())
                    if decoded != entity.group():
                        self.emit(decoded, pos)
                        pos = entity.end()
                        continue
            self.emit(char, pos)
            pos += 1
        _process_emphasis(delimiters)

    def link(self, pos: int, end: int) -> tuple[int, int, int] | None:
        """(label start, label end, link end) for an inline or defined reference link at `[`."""
        src = self.src
        level = 1
        scan = pos + 1
        while scan < end:
            char = src[scan]
            if char == "\\":
                scan += 2
                continue
            if char == "`":
                run_end = scan
                while run_end < end and src[run_end] == "`":
                    run_end += 1
                run = run_end - scan
                closing = src.find("`" * run, run_end, end)
                scan = closing + run if closing >= 0 else run_end
                continue
            if char == "[":
                level += 1
            elif char == "]":
                level -= 1
                if level == 0:
                    break
            scan += 1
        else:
            return None
        if level != 0:
            return None
        label_end = scan
        after = label_end + 1
        if after < end and src[after] == "(":
            depth = 0
            cursor = after + 1
            while cursor < end and src[cursor] in " \t\n":
                cursor += 1
            if cursor < end and src[cursor] == "<":
                close = src.find(">", cursor, end)
                if close < 0:
                    return None
                cursor = close + 1
            else:
                while cursor < end:
                    char = src[cursor]
                    if char == "\\" and cursor + 1 < end:
                        cursor += 2
                        continue
                    if char == "(":
                        depth += 1
                    elif char == ")":
                        if depth == 0:
                            break
                        depth -= 1
                    elif char in " \t\n":
                        break
                    cursor += 1
            while cursor < end and src[cursor] in " \t\n":
                cursor += 1
            if cursor < end and src[cursor] in "\"'(":
                quote = ")" if src[cursor] == "(" else src[cursor]
                close = cursor + 1
                while close < end and src[close] != quote:
                    close += 2 if src[close] == "\\" else 1
                if close >= end:
                    return None
                cursor = close + 1
                while cursor < end and src[cursor] in " \t\n":
                    cursor += 1
            if cursor < end and src[cursor] == ")":
                return pos + 1, label_end, cursor + 1
        if not self.refs:
            return None
        if after < end and src[after] == "[":
            close = src.find("]", after + 1, end)
            if close >= 0:
                reference = src[after + 1 : close] or src[pos + 1 : label_end]
                if _norm_label(reference) in self.refs:
                    return pos + 1, label_end, close + 1
                return None
        if _norm_label(src[pos + 1 : label_end]) in self.refs:
            return pos + 1, label_end, label_end + 1
        return None


def _process_emphasis(delimiters: list[dict]) -> None:
    """markdown-it `processDelimiters` for `*` only; marks every delimiter that becomes a tag."""
    bottoms = [-1] * 6
    header = 0
    last_token = -2
    jumps: list[int] = []
    for closer_index, closer in enumerate(delimiters):
        jumps.append(0)
        if last_token != closer["token"] - 1:
            header = closer_index
        last_token = closer["token"]
        if not closer["close"]:
            continue
        slot = (3 if closer["open"] else 0) + closer["length"] % 3
        minimum = bottoms[slot]
        opener_index = header - jumps[header] - 1
        new_minimum = opener_index
        while opener_index > minimum:
            opener = delimiters[opener_index]
            if opener["open"] and opener["end"] < 0:
                odd = False
                if (
                    (opener["close"] or closer["open"])
                    and (opener["length"] + closer["length"]) % 3 == 0
                    and (opener["length"] % 3 != 0 or closer["length"] % 3 != 0)
                ):
                    odd = True
                if not odd:
                    last_jump = (
                        jumps[opener_index - 1] + 1
                        if opener_index > 0 and not delimiters[opener_index - 1]["open"]
                        else 0
                    )
                    jumps[closer_index] = closer_index - opener_index + last_jump
                    jumps[opener_index] = last_jump
                    closer["open"] = False
                    opener["end"] = closer_index
                    opener["close"] = False
                    new_minimum = -1
                    last_token = -2
                    break
            opener_index -= jumps[opener_index] + 1
        if new_minimum != -1:
            bottoms[(3 if closer["open"] else 0) + closer["length"] % 3] = new_minimum
    for delimiter in delimiters:
        if delimiter["end"] >= 0:
            delimiter["matched"] = True
            delimiters[delimiter["end"]]["matched"] = True


_RAW_REMOVE = re.compile(
    r"<pre[\s>][\s\S]*?</pre>|<code[\s>][\s\S]*?</code>|<!--[\s\S]*?-->|<[^>]*>"
)
_RAW_ENTITY = re.compile(r"&#[xX]([0-9a-fA-F]+);|&#([0-9]+);|&(amp|lt|gt|quot|#39);")


def _raw_visible(block: list[tuple[int, str]]) -> list[tuple[str, int]]:
    """Visible characters of an HTML block: pre/code, comments and tags removed."""
    text = "\n".join(content for _, content in block)
    lines: list[int] = []
    for number, content in block:
        lines.extend([number] * (len(content) + 1))
    keep = [True] * len(text)
    for match in _RAW_REMOVE.finditer(text):
        for index in range(match.start(), match.end()):
            keep[index] = False
    return [(char, lines[index]) for index, char in enumerate(text) if keep[index]]


def unrendered_strong(text: str) -> list[int]:
    """Line number of every `**` that a CommonMark renderer leaves as visible asterisks.

    Defined as the count markdown-it's rendered HTML shows once <pre>, <code>, comments and tags
    are removed and entities decoded. Escaped `\\*\\*` is visible too, and counted.
    """
    lines = _blank_frontmatter(text.split("\n"))
    refs = _reference_labels(lines)
    visible: list[tuple[str, int]] = []
    for kind, block in _blocks(lines):
        if kind == "raw":
            visible.extend(_raw_visible(block))
        else:
            src = "\n".join(content for _, content in block)
            linemap: list[int] = []
            for number, content in block:
                linemap.extend([number] * (len(content) + 1))
            inline = _Inline(src, refs)
            inline.scope(0, len(src))
            hidden = False
            for shown, at, delimiter in inline.items:
                if shown == "\x01":
                    hidden = True
                    continue
                if shown == "\x02":
                    hidden = False
                    continue
                if hidden or (delimiter is not None and delimiter["matched"]):
                    continue
                for char in shown:
                    visible.append(
                        (char, linemap[at] if at < len(linemap) else block[-1][0])
                    )
        visible.append(("\n", 0))
    found: list[int] = []
    index = 0
    while index < len(visible) - 1:
        if visible[index][0] == "*" and visible[index + 1][0] == "*":
            found.append(visible[index][1])
            index += 2
        else:
            index += 1
    return found


# ---------------------------------------------------------------- entry points


def scan_markdown(text: str, lang: str) -> list[Finding]:
    """Every finding for one Markdown document, with 1-based line numbers of the file."""
    if lang not in LANGS:
        return []
    lines = _blank_frontmatter(text.split("\n"))
    found: list[Finding] = []
    d1 = RULE_BY_ID["D1"]
    for line in unrendered_strong(text):
        found.append(Finding(line, "D1", d1.level, d1.message))
    found.extend(_structural_findings(_prose_view(lines), lang))
    return sorted(found, key=lambda finding: (finding.line, finding.rule))


# The same marker syntax as the Hub's audit_public_output.py, which is authoritative inside the Hub.
# Duplicated here so this file stays copyable on its own. `ai-style-warn` precedes `ai-style` so
# the longer name is not read as the shorter one.
ALLOW = re.compile(r"<!--[^>]*?allow:(ai-style-warn|ai-style|all)[^>]*?-->")
FILE_ALLOW = re.compile(r"audit-file-allow:\s*([a-z-]+(?:\s*,\s*[a-z-]+)*)")
FILE_ALLOW_SCAN_LINES = 40
SKIP_DIR_NAMES = {"node_modules", ".venv", "venv", "__pycache__", "semantic-review"}


def _iter_markdown(paths: list[Path], excludes: list[str]):
    for given in paths:
        if given.is_file():
            yield given, given.name
            continue
        for path in sorted(given.rglob("*.md")):
            relative = path.relative_to(given)
            if any(
                part.startswith(".") or part in SKIP_DIR_NAMES
                for part in relative.parts[:-1]
            ):
                continue
            if any(
                fnmatch.fnmatch(relative.as_posix(), pattern) for pattern in excludes
            ):
                continue
            yield path, relative.as_posix()


def scan_file(path: Path, relative: str) -> tuple[str, list[Finding]]:
    """(language, findings) for one file, honouring allow markers."""
    text = path.read_text(encoding="utf-8")
    lines = text.split("\n")
    lang = language_of(relative, text)
    file_allowed: set[str] = set()
    for line in lines[:FILE_ALLOW_SCAN_LINES]:
        match = FILE_ALLOW.search(line)
        if match:
            file_allowed.update(part.strip() for part in match.group(1).split(","))
    kept: list[Finding] = []
    for finding in scan_markdown(text, lang):
        category = CATEGORY_FOR_LEVEL[finding.level]
        line = (
            _mask_code_spans(lines[finding.line - 1])
            if finding.line <= len(lines)
            else ""
        )
        allowed = {match.group(1) for match in ALLOW.finditer(line)} | file_allowed
        if category in allowed or "all" in allowed:
            continue
        kept.append(finding)
    return lang, kept


def summarize(results: list[tuple[str, str, list[Finding]]], top: int) -> str:
    counts: dict[tuple[str, str, str], int] = {}
    for _relative, lang, findings in results:
        for finding in findings:
            key = (CATEGORY_FOR_LEVEL[finding.level], lang, finding.rule)
            counts[key] = counts.get(key, 0) + 1
    order = {rule.id: index for index, rule in enumerate(RULES)}
    out = [
        "| category | lang | rule | findings |",
        "|---|---|---|---:|",
    ]
    for (category, lang, rule), count in sorted(
        counts.items(), key=lambda item: (item[0][0], item[0][1], order[item[0][2]])
    ):
        out.append(f"| {category} | {lang} | {rule} | {count} |")
    out.append("")
    scanned = {lang: 0 for lang in LANGS}
    for _relative, lang, _findings in results:
        if lang in scanned:
            scanned[lang] += 1
    out.append(
        "Scanned: "
        + ", ".join(f"{lang} {count} file(s)" for lang, count in scanned.items())
        + f", {sum(counts.values())} finding(s)."
    )
    out.append("")
    ranked = sorted(
        (item for item in results if item[2]),
        key=lambda item: (-len(item[2]), item[0]),
    )[:top]
    out.append("| file | lang | findings | fail-level |")
    out.append("|---|---|---:|---:|")
    for relative, lang, findings in ranked:
        fails = sum(1 for finding in findings if finding.level == "fail")
        out.append(f"| {relative} | {lang} | {len(findings)} | {fails} |")
    return "\n".join(out)


def selftest() -> int:
    failures: list[str] = []
    for rule in RULES:
        if not rule.positive or not rule.negative:
            failures.append(f"{rule.id}: needs a positive and a negative example")
        for lang, document in rule.positive:
            if rule.id not in {f.rule for f in scan_markdown(document, lang)}:
                failures.append(f"{rule.id}: silent on its positive {document[:40]!r}")
        for lang, document in rule.negative:
            if rule.id in {f.rule for f in scan_markdown(document, lang)}:
                failures.append(f"{rule.id}: fires on its negative {document[:40]!r}")
    if (
        len(
            unrendered_strong(
                "上は**「自分の構成」**で引く。次は**自分の構成**で引く。\n"
            )
        )
        < 1
    ):
        failures.append("D1: the bracketed-bold sentence is not reported")
    for failure in failures:
        print(f"selftest: {failure}", file=sys.stderr)
    if failures:
        return 1
    print(
        f"selftest: {len(RULES)} rule(s) fire on their positives and not their negatives"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "paths", nargs="*", type=Path, help="files or directories (*.md)"
    )
    parser.add_argument(
        "--summary", action="store_true", help="print a Markdown count table"
    )
    parser.add_argument("--top", type=int, default=10, help="files listed in --summary")
    parser.add_argument(
        "--fail", action="store_true", help="exit 1 on a fail-level finding"
    )
    parser.add_argument(
        "--exclude", action="append", default=[], help="glob, relative path"
    )
    parser.add_argument(
        "--selftest", action="store_true", help="check every rule's examples"
    )
    args = parser.parse_args(argv)
    if args.selftest:
        return selftest()
    if not args.paths:
        parser.error("give at least one file or directory, or --selftest")
    results: list[tuple[str, str, list[Finding]]] = []
    for path, relative in _iter_markdown(args.paths, args.exclude):
        lang, findings = scan_file(path, relative)
        results.append((relative, lang, findings))
    if args.summary:
        print(summarize(results, args.top))
    else:
        for relative, _lang, findings in results:
            for finding in findings:
                category = CATEGORY_FOR_LEVEL[finding.level]
                print(
                    f"{relative}:{finding.line}: [{category}] {finding.rule} {finding.message}"
                )
    has_fail = any(f.level == "fail" for _r, _l, findings in results for f in findings)
    return 1 if args.fail and has_fail else 0


if __name__ == "__main__":
    sys.exit(main())
